-
    label: 'Каталог'
    name: 'ns_catalog_settings'
    parent: 'settings'
    env: 'dev'
    pages:
        -
            label: 'Типы данных'
            action: 'types:index'
        -
            label: 'Каталоги'
            action: 'catalogs:index'
