blocks:
    -
        name: NSCatalogBundle:Blocks:mainItemsBlock
        title: Товары на главной странице
        form: "ns_catalogbundle_blockmainitemstype"
        template: NSCatalogBundle:Blocks:mainItemsBlock.phtml.twig
        settingsFormClass: NS\CatalogBundle\Block\Settings\MainItemsBlockSettingsForm
        settingsModelClass: NS\CatalogBundle\Block\Settings\MainItemsBlockSettingsModel
    -
        name: NSCatalogBundle:Blocks:newItemsBlock
        title: Новинки
        form: "ns_catalogbundle_blocknewitemstype"
        template: NSCatalogBundle:Blocks:newItemsBlock.phtml.twig
        settingsFormClass: NS\CatalogBundle\Block\Settings\NewItemsBlockSettingsForm
        settingsModelClass: NS\CatalogBundle\Block\Settings\NewItemsBlockSettingsModel
    -
        name: NSCatalogBundle:Blocks:categoriesMenuBlock
        title: Меню категорий
        form: "ns_catalogbundle_blockcategoriesmenutype"
        template: NSCatalogBundle:Blocks:categoriesMenuBlock.phtml.twig
        settingsFormClass: NS\CatalogBundle\Block\Settings\CategoriesMenuBlockSettingsForm
        settingsModelClass: NS\CatalogBundle\Block\Settings\CategoriesMenuBlockSettingsModel
    -
        name: NSCatalogBundle:Blocks:categoriesBlock
        title: Категории
        form: "ns_catalogbundle_blockcategoriestype"
        template: NSCatalogBundle:Blocks:categoriesBlock.phtml.twig
        settingsFormClass: NS\CatalogBundle\Block\Settings\CategoriesBlockSettingsForm
        settingsModelClass: NS\CatalogBundle\Block\Settings\CategoriesBlockSettingsModel
