blocks:
    -
        name: NSCatalogBundle:Blocks:categoriesMenuBlock
        title: Меню категорий
        settingsFormClass: NS\CatalogBundle\Block\Settings\CategoriesMenuBlockSettingsForm
        settingsModelClass: NS\CatalogBundle\Block\Settings\CategoriesMenuBlockSettingsModel
        template: NSCatalogBundle:Blocks:categoriesMenuBlock.html.twig
        cache:
            entities: [NS\CatalogBundle\Entity\Category]
    -
        name: NSCatalogBundle:Blocks:categoriesBlock
        title: Категории
        settingsFormClass: NS\CatalogBundle\Block\Settings\CategoriesBlockSettingsForm
        settingsModelClass: NS\CatalogBundle\Block\Settings\CategoriesBlockSettingsModel
        template: NSCatalogBundle:Blocks:categoriesBlock.html.twig
    -
        name: NSCatalogBundle:Blocks:itemsBlock
        title: Товары
        settingsFormClass: NS\CatalogBundle\Block\Settings\ItemsBlockSettingsForm
        settingsModelClass: NS\CatalogBundle\Block\Settings\ItemsBlockSettingsModel
    -
        name: NSCatalogBundle:Blocks:itemBlock
        title: Карточка товара
        settingsFormClass: NS\CatalogBundle\Block\Settings\ItemBlockSettingsForm
        settingsModelClass: NS\CatalogBundle\Block\Settings\ItemBlockSettingsModel
        template: NSCatalogBundle:Blocks:itemBlock.html.twig
    -
        name: NSCatalogBundle:Blocks:categoryBlock
        title: Карточка категории
        settingsFormClass: NS\CatalogBundle\Block\Settings\CategoryBlockSettingsForm
        settingsModelClass: NS\CatalogBundle\Block\Settings\CategoryBlockSettingsModel
    -
        name: NSCatalogBundle:Blocks:fullListBlock
        title: Полный список товаров
        settingsFormClass: NS\CmsBundle\Block\Settings\Generic\CountBlockSettingsForm
        settingsModelClass: NS\CmsBundle\Block\Settings\Generic\CountBlockSettingsModel
    -
        name: NSCatalogBundle:Blocks:searchBlock
        title: Поиск по товарам каталога
        settingsFormClass: NS\CatalogBundle\Block\Settings\SearchBlockSettingsForm
        settingsModelClass: NS\CatalogBundle\Block\Settings\SearchBlockSettingsModel