blocks:
    -
        name: NSCatalogBundle:Blocks:mainItemsBlock
        title: Товары на главной странице
        form: "ns_catalogbundle_blockmainitemstype"
        template: NSCatalogBundle:Blocks:mainItemsBlock.phtml.twig
        settingsFormClass: NS\CatalogBundle\Block\Settings\MainItemsBlockSettingsForm
        settingsModelClass: NS\CatalogBundle\Block\Settings\MainItemsBlockSettingsModel
