parameters:
    ns_catalog.settings.formtype.collection.class: 'NS\Catalog\Model\SettingsFormTypeCollection'

services:
    ns_catalog.settings.formtype.collection:
        class: %ns_catalog.settings.formtype.collection.class%
        tags:
            - { name: ns_properties.type }
