parameters:
#    ns_catalog.example.class: NS\CatalogBundle\Example

services:
#    ns_catalog.example:
#        class: %ns_catalog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
